### ISSUE TITLE
Cannot register for API key - broken link

### ISSUE THREAD

**Issue by jayqui** [sunlightlabs/sunlightapi#1]
This is supposed to be the link for signing up for an API key, but it appears to be malfunctioning: http://services.sunlightlabs.com/accounts/register/

**Comment by jayqui** [comment]
![image](https://cloud.githubusercontent.com/assets/10286362/20651931/52ea1d82-b4a4-11e6-8656-21d64c51044e.png)

**Comment by krusynth** [comment]
@jayqui Sunlight Labs has closed, and the tools have moved to other owners.  More on this here:

https://sunlightfoundation.com/2016/11/01/sunlight-labs-update-nonprofits-step-up-to-preserve-tools-for-transparency/
